# Generated by Django 6.0.4 on 2026-04-19 15:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acreedor', models.CharField(help_text='A quién le debes.', max_length=100)),
                ('monto_original', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('nota', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Deuda',
                'verbose_name_plural': 'Deudas',
                'ordering': ['-fecha', 'acreedor'],
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('categoria', models.CharField(choices=[('comida', 'Comida'), ('transporte', 'Transporte'), ('diversion', 'Diversión'), ('personal', 'Personal'), ('hogar', 'Hogar'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='GastoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dia_pago', models.PositiveSmallIntegerField(default=1, help_text='Día del mes en que vence el pago (1-31).')),
                ('activo', models.BooleanField(default=True)),
                ('nota', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Gasto fijo',
                'verbose_name_plural': 'Gastos fijos',
                'ordering': ['dia_pago', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fuente', models.CharField(blank=True, help_text='De dónde viene (sueldo, freelance, venta, etc.)', max_length=100)),
                ('nota', models.CharField(blank=True, max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PagoDeuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nota', models.CharField(blank=True, max_length=255)),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ahorros.deuda')),
            ],
            options={
                'verbose_name': 'Pago de deuda',
                'verbose_name_plural': 'Pagos de deudas',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
