# Generated by Django 6.0.4 on 2026-04-19 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahorros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deseo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prioridad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
                ('nota', models.CharField(blank=True, max_length=255)),
                ('comprado', models.BooleanField(default=False)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('gasto', models.ForeignKey(blank=True, help_text='Gasto generado al marcar el deseo como comprado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deseos', to='ahorros.gasto')),
            ],
            options={
                'verbose_name': 'Deseo',
                'verbose_name_plural': 'Deseos',
                'ordering': ['comprado', '-creado_en'],
            },
        ),
    ]
