# Generated by Django 6.0.2 on 2026-06-26 03:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ahorros', '0002_deseo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('gasto', 'Gasto'), ('gasto_fijo', 'Gasto fijo'), ('deuda', 'Deuda'), ('pago_deuda', 'Pago de deuda'), ('deseo', 'Deseo'), ('nota', 'Nota'), ('recordatorio', 'Recordatorio')], max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=255)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historial',
                'verbose_name_plural': 'Historial',
                'ordering': ['-fecha', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('contenido', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_recordatorio', models.DateField()),
                ('completado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recordatorio',
                'verbose_name_plural': 'Recordatorios',
                'ordering': ['completado', 'fecha_recordatorio', '-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='deseo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='evidencia/deseos/'),
        ),
        migrations.AddField(
            model_name='deuda',
            name='evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='evidencia/deudas/'),
        ),
        migrations.AddField(
            model_name='deuda',
            name='plazo_meses',
            field=models.PositiveSmallIntegerField(default=3, help_text='Cuántos meses planeas pagar esta deuda.'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='evidencia/gastos/'),
        ),
        migrations.AddField(
            model_name='gastofijo',
            name='evidencia',
            field=models.ImageField(blank=True, null=True, upload_to='evidencia/fijos/'),
        ),
    ]
